- name: sandbox-logging-bash-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master

- name: sandbox-logging-msf-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master

- name: sandbox-logging-forward-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master

- name: chrony
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/chrony.git
  scm: git
  version: 1.0.1

- name: hosts-aliases
  src: https://gitlab.ics.muni.cz/muni-kypo/ansible-roles/hosts-aliases.git
  scm: git
  version: 1.0.0

- name: kypo-user-access
  src: https://gitlab.ics.muni.cz/muni-kypo-crp/backend-python/ansible-networking-stage/kypo-user-access.git
  scm: git
  version: 470b8b91
