- name: sandbox-logging-bash-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master

- name: sandbox-logging-msf-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master

- name: sandbox-logging-forward-modern
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging
  scm: git
  version: master
